update actions

diff --git a/.github/workflows/pr-feat-to-main.yml b/.github/workflows/pr-feat-to-main.yml
--- a/.github/workflows/pr-feat-to-main.yml
+++ b/.github/workflows/pr-feat-to-main.yml
@@ -7,7 +7,6 @@ on:
 
 jobs:
   check-confluence-link:
-    # Run on any branch merging into "main"
     runs-on: ubuntu-latest
     steps:
       - name: Check for Confluence Release Plan Link
@@ -21,7 +20,7 @@ jobs:
           # Check for Confluence Release Plan link with domain ajaib.atlassian.net and format YYYY-MM-DD in the link text
           if [[ ! "$DESCRIPTION" =~ https://ajaib.atlassian.net/wiki/.+[0-9]{4}-[0-9]{2}-[0-9]{2} ]]; then
             echo "A Confluence release plan link with the domain https://ajaib.atlassian.net/wiki/ and a date in the format YYYY-MM-DD is missing in the PR description."
-            exit 1
+            exit 1  # Exit with an error status to fail the action
           fi
 
           echo "Confluence release plan link found in the PR description."
