add workflow

diff --git a/.github/workflows/pr-feat-to-main.yml b/.github/workflows/pr-feat-to-main.yml
--- a/.github/workflows/pr-feat-to-main.yml
+++ b/.github/workflows/pr-feat-to-main.yml
@@ -3,7 +3,7 @@ name: Check Confluence Release Plan Link
 on:
   pull_request:
     branches:
-      - stg
+      - main
 
 jobs:
   check-confluence-link:
@@ -17,24 +17,10 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             "${{ github.event.pull_request.url }}" | jq -r .body)
 
-          # Get the current date in YYYY-MM-DD format
-          CURRENT_DATE=$(date +'%Y-%m-%d')
-
-          # Extract the link with the date from the PR description
-          LINK=$(echo "$DESCRIPTION" | grep -o 'https://ajaib.atlassian.net/wiki/.+\[[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\]')
-
-          if [[ -z "$LINK" ]]; then
-            echo "A Confluence release plan link with the domain https://ajaib.atlassian.net/wiki/ is missing in the PR description."
-            exit 1
+          # Check for a Confluence link in the PR description
+          if [[ ! "$DESCRIPTION" =~ https://ajaib\.atlassian\.net/wiki/ ]]; then
+            echo "::error ::A Confluence release plan link is missing in the PR description."
+            exit 1  # Exit with an error status to fail the action
           fi
 
-          # Extract the date from the link
-          LINK_DATE=$(echo "$LINK" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')
-
-          # Check if the date matches the current date
-          if [[ "$LINK_DATE" != "$CURRENT_DATE" ]]; then
-            echo "The date in the Confluence link ($LINK_DATE) does not match the current date ($CURRENT_DATE)."
-            exit 1
-          fi
-
-          echo "Confluence release plan link found and date matches the current date."
+          echo "Confluence release plan link found in the PR description."
